name: GitHub Commit To Trello Comment
run-name: ${{ github.actor }} is attaching commits to Trello
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dalezak/github-commit-to-trello-card@main
        with:
          trello-api-key: ${{ secrets.TRELLO_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_TOKEN }}
          trello-board-id: ${{ secrets.TRELLO_BOARD }}
          trello-card-action: "Attachment"
          trello-list-name-commit: "In Progress"
          trello-list-name-pr-open: "To Do"
          trello-list-name-pr-closed: "Testing"